consultas = [
    'load "dataset/dataset_pacientes.csv";\nfilter column "edad" > 30;\naggregate sum column "salario";\nprint;',
    'load "dataset/dataset_pacientes.csv";\nfilter column "dias_laborados" >= 25;\naggregate average column "salario";\nprint;',
    'load "dataset/dataset_pacientes.csv";\nfilter column "diagnostico" == "asma";\naggregate count column "id_paciente";\nprint;',
    'load "dataset/dataset_pacientes.csv";\nfilter column "pais" == "Perú";\naggregate sum column "salario";\nprint;',
    'load "dataset/dataset_pacientes.csv";\nfilter column "edad" < 40;\naggregate average column "dias_laborados";\nprint;',
    'load "dataset/dataset_pacientes.csv";\nfilter column "diagnostico" == "diabetes";\naggregate count column "id_paciente";\nprint;',
    'load "dataset/dataset_pacientes.csv";\nfilter column "salario" > 1200;\naggregate sum column "dias_laborados";\nprint;',
    'load "dataset/dataset_pacientes.csv";\nfilter column "pais" == "Chile";\naggregate count column "id_paciente";\nprint;',
    'load "dataset/dataset_pacientes.csv";\nfilter column "edad" >= 60;\naggregate average column "salario";\nprint;',
    'load "dataset/dataset_pacientes.csv";\nfilter column "diagnostico" == "hipertensión";\naggregate count column "id_paciente";\nprint;',
    'load "dataset/dataset_pacientes.csv";\nfilter column "dias_laborados" < 20;\naggregate sum column "salario";\nprint;',
    'load "dataset/dataset_pacientes.csv";\nfilter column "pais" == "Argentina";\naggregate count column "id_paciente";\nprint;',
    'load "dataset/dataset_pacientes.csv";\nfilter column "edad" > 50;\naggregate average column "dias_laborados";\nprint;',
    'load "dataset/dataset_pacientes.csv";\nfilter column "diagnostico" == "ansiedad";\naggregate count column "id_paciente";\nprint;',
    'load "dataset/dataset_pacientes.csv";\nfilter column "salario" <= 1100;\naggregate sum column "dias_laborados";\nprint;',
    'load "dataset/dataset_pacientes.csv";\nfilter column "pais" == "México";\naggregate count column "id_paciente";\nprint;',
    'load "dataset/dataset_pacientes.csv";\nfilter column "edad" < 25;\naggregate average column "salario";\nprint;',
    'load "dataset/dataset_pacientes.csv";\nfilter column "diagnostico" == "depresión";\naggregate count column "id_paciente";\nprint;',
    'load "dataset/dataset_pacientes.csv";\nfilter column "dias_laborados" >= 30;\naggregate sum column "salario";\nprint;',
    'load "dataset/dataset_pacientes.csv";\nfilter column "pais" == "Colombia";\naggregate count column "id_paciente";\nprint;',
    'load "dataset/dataset_pacientes.csv";\nfilter column "edad" between 30 and 50;\naggregate average column "dias_laborados";\nprint;',
    'load "dataset/dataset_pacientes.csv";\nfilter column "diagnostico" == "asma";\naggregate count column "id_paciente";\nprint;',
    'load "dataset/dataset_pacientes.csv";\nfilter column "salario" > 1400;\naggregate sum column "dias_laborados";\nprint;',
    'load "dataset/dataset_pacientes.csv";\nfilter column "pais" == "Chile";\naggregate count column "id_paciente";\nprint;',
    'load "dataset/dataset_pacientes.csv";\nfilter column "edad" >= 40;\naggregate average column "salario";\nprint;',
    'load "dataset/dataset_pacientes.csv";\nfilter column "diagnostico" == "hipertensión";\naggregate count column "id_paciente";\nprint;',
    'load "dataset/dataset_pacientes.csv";\nfilter column "dias_laborados" < 15;\naggregate sum column "salario";\nprint;',
    'load "dataset/dataset_pacientes.csv";\nfilter column "pais" == "Argentina";\naggregate count column "id_paciente";\nprint;',
    'load "dataset/dataset_pacientes.csv";\nfilter column "edad" > 60;\naggregate average column "dias_laborados";\nprint;',
    'load "dataset/dataset_pacientes.csv";\nfilter column "diagnostico" == "ansiedad";\naggregate count column "id_paciente";\nprint;',
    'load "dataset/dataset_pacientes.csv";\nfilter column "salario" <= 1000;\naggregate sum column "dias_laborados";\nprint;',
    'load "dataset/dataset_pacientes.csv";\nfilter column "pais" == "México";\naggregate count column "id_paciente";\nprint;',
    'load "dataset/dataset_pacientes.csv";\nfilter column "edad" < 35;\naggregate average column "salario";\nprint;',
    'load "dataset/dataset_pacientes.csv";\nfilter column "diagnostico" == "depresión";\naggregate count column "id_paciente";\nprint;',
    'load "dataset/dataset_pacientes.csv";\nfilter column "dias_laborados" >= 10;\naggregate sum column "salario";\nprint;',
    'load "dataset/dataset_pacientes.csv";\nfilter column "pais" == "Colombia";\naggregate count column "id_paciente";\nprint;',
    'load "dataset/dataset_pacientes.csv";\nfilter column "edad" between 20 and 40;\naggregate average column "dias_laborados";\nprint;',
    'load "dataset/dataset_pacientes.csv";\nfilter column "diagnostico" == "asma";\naggregate count column "id_paciente";\nprint;',
    'load "dataset/dataset_pacientes.csv";\nfilter column "salario" > 1300;\naggregate sum column "dias_laborados";\nprint;',
]

# Generar los archivos .dsl
for i, consulta in enumerate(consultas, start=1):
    filename = f"scripts/consulta{i}.dsl"
    with open(filename, "w", encoding="utf-8") as file:
        file.write(consulta)